#!/usr/bin/env bash
set -euo pipefail

resolve_dir() {
	local var_name="$1"
	local default_path="$2"
	local path="${!var_name:-$default_path}"

	if [ ! -d "$path" ]; then
		echo "Missing $var_name directory: $path" >&2
		echo "Clone it as a sibling repo or set $var_name to an existing checkout." >&2
		exit 1
	fi

	cd "$path" && pwd
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANUAL_DIR="$(resolve_dir MANUAL_DIR "$SCRIPT_DIR/../riscv-isa-manual")"
ASM_MANUAL_DIR="$(resolve_dir ASM_MANUAL_DIR "$SCRIPT_DIR/../riscv-asm-manual")"
SBI_DOC_DIR="$(resolve_dir SBI_DOC_DIR "$SCRIPT_DIR/../riscv-sbi-doc")"
IOMMU_DIR="$(resolve_dir IOMMU_DIR "$SCRIPT_DIR/../riscv-iommu")"
TRACE_SPEC_DIR="$(resolve_dir TRACE_SPEC_DIR "$SCRIPT_DIR/../riscv-trace-spec")"
ASCIIDOCTOR_MDX="${ASCIIDOCTOR_MDX:-/home/dmg/projects/asciidoctor/wrappers/asciidoctor-mdx}"

if [ -z "${ASDF_RUBY_VERSION:-}" ] && [ -f "$MANUAL_DIR/.tool-versions" ]; then
	RUBY_VERSION="$(awk '$1 == "ruby" { print $2; exit }' "$MANUAL_DIR/.tool-versions")"
	if [ -n "$RUBY_VERSION" ]; then
		export ASDF_RUBY_VERSION="$RUBY_VERSION"
	fi
fi

# Create temp wrapper adoc files that prepend symbols.adoc to each volume.
# This is necessary because the per-volume files (unpriv.adoc, priv/priv.adoc)
# depend on the parent riscv-spec.adoc to include symbols.adoc first — we
# replicate that here without touching the upstream source.
WRAP_DIR="$(mktemp -d)"
SBI_REVISION_DIR="$SBI_DOC_DIR/autogenerated"
SBI_REVISION_SNIPPET="$SBI_REVISION_DIR/revision.adoc-snippet"
SBI_REVISION_BACKUP="$WRAP_DIR/sbi-revision.adoc-snippet"
SBI_REVISION_CLEANUP=0
SBI_REVISION_EXISTED=0
SBI_REVISION_DIR_EXISTED=0

cleanup() {
	local status=$?

	if [ "${SBI_REVISION_CLEANUP:-0}" = "1" ]; then
		if [ "${SBI_REVISION_EXISTED:-0}" = "1" ]; then
			mkdir -p "$SBI_REVISION_DIR" || status=$?
			cp -p "$SBI_REVISION_BACKUP" "$SBI_REVISION_SNIPPET" || status=$?
		else
			rm -f "$SBI_REVISION_SNIPPET" || status=$?
			if [ "${SBI_REVISION_DIR_EXISTED:-0}" = "0" ]; then
				rmdir "$SBI_REVISION_DIR" 2>/dev/null || true
			fi
		fi
	fi

	rm -rf "$WRAP_DIR" || status=$?
	exit "$status"
}
trap cleanup EXIT

cat >"$WRAP_DIR/unpriv.adoc" <<EOF
include::$MANUAL_DIR/src/symbols.adoc[]
include::$MANUAL_DIR/src/unpriv.adoc[]
EOF

cat >"$WRAP_DIR/priv.adoc" <<EOF
include::$MANUAL_DIR/src/symbols.adoc[]
include::$MANUAL_DIR/src/priv/priv.adoc[]
EOF

DATE="$(date +%Y%m%d)"

COMMON_MDX_OPTS=(
	--trace
	-a sectnums
	-a "revnumber=$DATE"
	-a 'revremark=DRAFT---NOT AN OFFICIAL RELEASE'
	-a docinfo=shared
)

ISA_MDX_OPTS=(
	"${COMMON_MDX_OPTS[@]}"
	-a "bibtex-file=$MANUAL_DIR/src/resources/riscv-spec.bib"
	-a "github-edit-url-base=https://github.com/riscv/riscv-isa-manual/blob/main"
	-a "github-local-root=$MANUAL_DIR"
	-a 'mdx-images-url=/img/riscv-isa/'
	-a "mdx-images-root=$MANUAL_DIR/src/images"
)

MDX_REQUIRES=(
	--require=asciidoctor-bibtex
	--require=asciidoctor-lists
	--require=asciidoctor-sail
)

copy_generated_docs() {
	local source_build_dir="$1"
	local docs_dir="$2"

	mkdir -p "$docs_dir"
	rm -f "$docs_dir"/*.mdx "$docs_dir/sidebar.json"
	cp "$source_build_dir"/*.mdx "$docs_dir/"
	cp "$source_build_dir/sidebar.json" "$docs_dir/"
}

copy_images() {
	local source_dir="$1"
	local target_dir="$2"

	mkdir -p "$target_dir"
	if [ -d "$source_dir" ]; then
		(
			shopt -s dotglob nullglob
			for source_path in "$source_dir"/*; do
				if [ "$(basename "$source_path")" = ".gitignore" ]; then
					continue
				fi
				cp -r "$source_path" "$target_dir/"
			done
		)
	fi
}

normalize_empty_doc_id() {
	local build_dir="$1"
	local docs_subdir="$2"
	local hidden_doc="$build_dir/.mdx"
	local index_doc="$build_dir/index.mdx"
	local sidebar_file="$build_dir/sidebar.json"
	local empty_id="$docs_subdir/"
	local index_id="$docs_subdir/index"

	if [ ! -f "$hidden_doc" ]; then
		return 0
	fi

	mv "$hidden_doc" "$index_doc"

	python3 - "$index_doc" "$sidebar_file" "$empty_id" "$index_id" <<'PY'
import json
import sys
from pathlib import Path

index_path = Path(sys.argv[1])
sidebar_path = Path(sys.argv[2])
old_id = sys.argv[3]
new_id = sys.argv[4]

mdx_lines = index_path.read_text(encoding="utf-8").splitlines(keepends=True)
if mdx_lines and mdx_lines[0].strip() == "---":
    frontmatter_end = next(
        (idx for idx, line in enumerate(mdx_lines[1:], start=1) if line.strip() == "---"),
        None,
    )
    if frontmatter_end is not None:
        for idx in range(1, frontmatter_end):
            if mdx_lines[idx].startswith("id:"):
                newline = "\n" if mdx_lines[idx].endswith("\n") else ""
                mdx_lines[idx] = "id: index" + newline
                break
        else:
            mdx_lines.insert(frontmatter_end, "id: index\n")
        index_path.write_text("".join(mdx_lines), encoding="utf-8")

with sidebar_path.open(encoding="utf-8") as sidebar_file:
    sidebar = json.load(sidebar_file)


def rewrite_ids(node):
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "id" and value == old_id:
                node[key] = new_id
            else:
                rewrite_ids(value)
    elif isinstance(node, list):
        for item in node:
            rewrite_ids(item)


rewrite_ids(sidebar)

with sidebar_path.open("w", encoding="utf-8") as sidebar_file:
    json.dump(sidebar, sidebar_file, indent=2, ensure_ascii=False)
    sidebar_file.write("\n")
PY
}

build_spec_mdx() {
	local repo_dir="$1"
	local root_doc="$2"
	local build_subdir="$3"
	local docs_subdir="$4"
	local sidebar_dir="$5"
	local image_url="$6"
	local image_root="$7"
	local edit_url_base="$8"
	shift 8

	local build_dir="$WRAP_DIR/build/$build_subdir"

	echo "Building $docs_subdir MDX..."
	mkdir -p "$build_dir"
	(
		cd "$repo_dir"
		LANG=C.utf8 "$ASCIIDOCTOR_MDX" \
			"${COMMON_MDX_OPTS[@]}" \
			-a "github-edit-url-base=$edit_url_base" \
			-a "github-local-root=$repo_dir" \
			-a "mdx-images-url=$image_url" \
			-a "mdx-images-root=$image_root" \
			-a "mdx-sidebar-dir=$sidebar_dir" \
			"$@" \
			-D "$build_dir" \
			"$root_doc"
	)

	normalize_empty_doc_id "$build_dir" "$docs_subdir"
	copy_generated_docs "$build_dir" "$SCRIPT_DIR/docs/$docs_subdir"
}

prepare_sbi_revision() {
	local commit_date
	local git_version

	if [ "$SBI_REVISION_CLEANUP" = "0" ]; then
		if [ -d "$SBI_REVISION_DIR" ]; then
			SBI_REVISION_DIR_EXISTED=1
		fi
		if [ -f "$SBI_REVISION_SNIPPET" ]; then
			cp -p "$SBI_REVISION_SNIPPET" "$SBI_REVISION_BACKUP"
			SBI_REVISION_EXISTED=1
		fi
		SBI_REVISION_CLEANUP=1
	fi

	commit_date="$(git -C "$SBI_DOC_DIR" show -s --format=%ci | cut -d ' ' -f 1)"
	git_version="$(git -C "$SBI_DOC_DIR" describe --tags --always 2>/dev/null || git -C "$SBI_DOC_DIR" rev-parse --short HEAD)"

	mkdir -p "$SBI_REVISION_DIR"
	{
		echo ":revdate: $commit_date"
		echo ":revnumber: $git_version"
	} >"$SBI_REVISION_SNIPPET"
}

# Run from MANUAL_DIR so the .tool-versions Ruby version is picked up by asdf.
cd "$MANUAL_DIR"

echo "Building unprivileged MDX..."
mkdir -p build/unpriv
LANG=C.utf8 "$ASCIIDOCTOR_MDX" \
	"${ISA_MDX_OPTS[@]}" "${MDX_REQUIRES[@]}" \
	-a "imagesdir=$MANUAL_DIR/src/images" \
	-a mdx-sidebar-dir=unprivileged \
	-D build/unpriv \
	"$WRAP_DIR/unpriv.adoc"

echo "Building privileged MDX..."
mkdir -p build/priv
LANG=C.utf8 "$ASCIIDOCTOR_MDX" \
	"${ISA_MDX_OPTS[@]}" "${MDX_REQUIRES[@]}" \
	-a "imagesdir=$MANUAL_DIR/src/images" \
	-a mdx-sidebar-dir=privileged \
	-D build/priv \
	"$WRAP_DIR/priv.adoc"

echo "Copying ISA docs to Docusaurus..."
copy_generated_docs "$MANUAL_DIR/build/unpriv" "$SCRIPT_DIR/docs/unprivileged"
copy_generated_docs "$MANUAL_DIR/build/priv" "$SCRIPT_DIR/docs/privileged"

build_spec_mdx \
	"$ASM_MANUAL_DIR" \
	"src/riscv-asm.adoc" \
	"asm-manual" \
	"asm-manual" \
	"asm-manual" \
	"/img/riscv-asm-manual/" \
	"$ASM_MANUAL_DIR/docs-resources/images" \
	"https://github.com/riscv-non-isa/riscv-asm-manual/blob/main" \
	--require=asciidoctor-lists

prepare_sbi_revision
build_spec_mdx \
	"$SBI_DOC_DIR" \
	"riscv-sbi.adoc" \
	"sbi" \
	"sbi" \
	"sbi" \
	"/img/riscv-sbi-doc/" \
	"$SBI_DOC_DIR/images" \
	"https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master" \
	-a "bibtex-file=$SBI_DOC_DIR/src/references.bib" \
	-a "imagesdir=$SBI_DOC_DIR" \
	--require=asciidoctor-bibtex

build_spec_mdx \
	"$IOMMU_DIR" \
	"src/riscv-iommu.adoc" \
	"iommu" \
	"iommu" \
	"iommu" \
	"/img/riscv-iommu/" \
	"$IOMMU_DIR/src/images" \
	"https://github.com/riscv-non-isa/riscv-iommu/blob/main" \
	-a "bibtex-file=$IOMMU_DIR/src/iommu.bib" \
	-a "imagesdir=$IOMMU_DIR/src" \
	--require=asciidoctor-bibtex \
	--require=asciidoctor-lists

build_spec_mdx \
	"$TRACE_SPEC_DIR" \
	"header.adoc" \
	"trace" \
	"trace" \
	"trace" \
	"/img/riscv-trace-spec/" \
	"$TRACE_SPEC_DIR/images" \
	"https://github.com/riscv-non-isa/riscv-trace-spec/blob/main"

echo "Copying images..."
copy_images "$MANUAL_DIR/src/images" "$SCRIPT_DIR/static/img/riscv-isa"
copy_images "$ASM_MANUAL_DIR/docs-resources/images" "$SCRIPT_DIR/static/img/riscv-asm-manual"
copy_images "$SBI_DOC_DIR/images" "$SCRIPT_DIR/static/img/riscv-sbi-doc"
copy_images "$IOMMU_DIR/src/images" "$SCRIPT_DIR/static/img/riscv-iommu"
copy_images "$TRACE_SPEC_DIR/images" "$SCRIPT_DIR/static/img/riscv-trace-spec"

echo "Done. Run 'bun run build' or 'bun run start' to rebuild the site."
