// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  unprivilegedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'unprivileged',
    },
  ],
  privilegedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'privileged',
    },
  ],
};

export default sidebars;
